// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameHistoryService.Migrations
{
    [DbContext(typeof(GameHistoryDbContext))]
    [Migration("20251010010644_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Common.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("GameMatchId")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GameMatchId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("Common.Entities.GameHistory", b =>
                {
                    b.Property<string>("MatchId")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MoveHistory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlayerUserIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PlayerUserIds");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WinnerUserId")
                        .HasColumnType("text");

                    b.HasKey("MatchId");

                    b.ToTable("GameHistories");
                });

            modelBuilder.Entity("Common.Entities.ChatMessage", b =>
                {
                    b.HasOne("Common.Entities.GameHistory", null)
                        .WithMany("ChatMessages")
                        .HasForeignKey("GameMatchId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Common.Entities.GameHistory", b =>
                {
                    b.Navigation("ChatMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
