// <auto-generated />
using System;
using System.Collections.Generic;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameHistoryService.Migrations
{
    [DbContext(typeof(GameHistoryDbContext))]
    [Migration("20251015204706_AddEmailSearch")]
    partial class AddEmailSearch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Common.Entities.GameHistory", b =>
                {
                    b.Property<string>("MatchId")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MoveHistory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("PlayerEmails")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<List<string>>("PlayerUserIds")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WinnerUserId")
                        .HasColumnType("text");

                    b.HasKey("MatchId");

                    b.HasIndex("PlayerEmails");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("PlayerEmails"), "GIN");

                    b.HasIndex("PlayerUserIds");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("PlayerUserIds"), "GIN");

                    b.ToTable("GameHistories", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
