services:
  xogamedb:
    image: redis:alpine

  xogameservice.api:
    image: ${DOCKER_REGISTRY-}xogameserviceapi
    build:
      context: .
      dockerfile: Services/XOGameService/XOGameService.API/Dockerfile
