services:

  rabbitmq:
    image: rabbitmq:3-management-alpine

  gamehistoryservicedb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4
      
  xogamedb:
    image: redis:alpine

  xogameservice.api:
    image: ${DOCKER_REGISTRY-}xogameserviceapi
    build:
      context: .
      dockerfile: Services/XOGameService/XOGameService.API/Dockerfile

  gamehistoryservice:
    image: ${DOCKER_REGISTRY-}gamehistoryservice
    build:
      context: .
      dockerfile: Services/GameHistoryService/Dockerfile

volumes:
  postgres_data:
  pgadmin_data:
  rabbitmq_data: