services:

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 4

  gamehistoryservicedb:
    container_name: gamehistorydb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin4444
      - POSTGRES_DB=GameHistoryServiceDb
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d GameHistoryServiceDb"]
      interval: 10s
      timeout: 5s
      retries: 4
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=bapop413@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin4444
      - POSTGRES_DB=GameHistoryServiceDb
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin


  xogamedb:
    container_name: xogamedb
    restart: always
    ports:
      - "6379:6379"

  xogameservice.api:
    container_name: xogame.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      - xogamedb
    ports:
      - "8001:8080"
    
  gamehistoryservice:
    container_name: gamehistoryservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "RabbitMQ:HostAddress=amqp://guest:guest@rabbitmq:5672"
      - "RabbitMQ:GameEndedQueue=game_ended-queue"
      - "RabbitMQ:ChatLogQueue=chat_log_queue"
      - "ConnectionStrings:DbConnectionString=Server=gamehistoryservicedb;Port=5432;Database=GameHistoryServiceDb;User Id=admin; Password=admin4444;"
    depends_on:
      rabbitmq:
        condition: service_healthy
      gamehistoryservicedb:
        condition: service_healthy
    ports:
      - "8002:80"