services:

  rabbitmq:
    image: rabbitmq:3-management-alpine

  gamehistoryservicedb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4
      
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always

  xogamedb:
    image: redis:alpine
    container_name: xogamedb
    restart: always
    ports:
      - "6379:6379"

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: userChat
      POSTGRES_PASSWORD: passChat
      POSTGRES_DB: chatdb
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  xogameservice.api:
    image: ${DOCKER_REGISTRY-}xogameserviceapi
    container_name: xogame.api
    build:
      context: .
      dockerfile: Services/XOGameService/XOGameService.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      - xogamedb
    ports:
      - "8001:8080"

  gamehistoryservice:
    image: ${DOCKER_REGISTRY-}gamehistoryservice
    build:
      context: .
      dockerfile: Services/GameHistoryService/Dockerfile

  authenticationservice:
    image: authenticationservice
    container_name: ludus-authenticationservice
    build:
      context: Services/AuthenticationService/AuthenticationService
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=Ludus;User Id=sa;Password=LudusBaza123!;TrustServerCertificate=True;
    depends_on:
      sqlserver:
        condition: service_healthy
    ports:
      - "7000:8080"
    restart: always
  
  ludusgateways:
    image: ${DOCKER_REGISTRY-}ludusgateways
    build:
      context: . 
      dockerfile: Services/ApiGateways/SPAGateways/Dockerfile

  chatservice:
    image: ${DOCKER_REGISTRY-}chatservice
    build:
      context: Services/Chat/ChatService
      dockerfile: Dockerfile
    depends_on:
      - postgres-db
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5432;Database=chatdb;Username=userChat;Password=passChat
    ports:
      - "5090:5090"

  matchmakingservice:
    image: ${DOCKER_REGISTRY-}matchmakingservice
    build:
      context: .
      dockerfile: Services/matchmaking/MatchmakingService/Dockerfile

volumes:
  mssql_data:
  postgres_data:
  pgadmin_data:
  rabbitmq_data:
