services:
  xogamedb:
    container_name: xogamedb
    restart: always
    image: redis:alpine
    ports:
      - "6379:6379"

  xogameservice.api:
    container_name: xogame.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "RedisCacheSettings:ConnectionString=xogamedb:6379"
    depends_on:
      - xogamedb
    ports:
      - "8001:8080"

  ludusgateways:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      - xogamedb
      - xogameservice.api
    ports:
      - "8010:8080"

  matchmakingservice:
    container_name: matchmakingservice
    build:
      context: .
      dockerfile: Services/Matchmaking/MatchmakingService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - RABBIT_HOST=rabbitmq
      - USER_GRPC_ADDRESS=http://user-service:5001
      - GAME_GRPC_ADDRESS=http://xogameservice.api:8080
    depends_on:
      - rabbitmq
      - xogameservice.api
    ports:
      - "5002:8080"
    networks:
      - ludus-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ludus-network

networks:
  ludus-network:
    driver: bridge
