services:
  xogamedb:
    image: redis:alpine

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: userChat
      POSTGRES_PASSWORD: passChat
      POSTGRES_DB: chatdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  xogameservice.api:
    image: ${DOCKER_REGISTRY-}xogameserviceapi
    build:
      context: .
      dockerfile: Services/XOGameService/XOGameService.API/Dockerfile

  ludusgateways:
    image: ${DOCKER_REGISTRY-}ludusgateways
    build:
      context: . 
      dockerfile: Services/ApiGateways/SPAGateways/Dockerfile

  chatservice:
    image: ${DOCKER_REGISTRY-}chatservice
    build:
      context: Services/ChatService
      dockerfile: Dockerfile
    depends_on:
      - postgres-db
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5432;Database=chatdb;Username=userChat;Password=passChat
    ports:
      - "5090:5090"

volumes:
  postgres-data:
