services:
  sqlserver:
    container_name: ludus-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=LudusBaza123!
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql/data
    user: root

  xogamedb:
    container_name: xogamedb
    restart: always
    image: redis:alpine
    ports:
      - "6379:6379"

  xogameservice.api:
    container_name: xogame.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "RedisCacheSettings:ConnectionString=xogamedb:6379"
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_Kestrel__Endpoints__Grpc__Protocols=Http2
      - ASPNETCORE_Kestrel__Endpoints__Grpc__Url=http://+:8080
      - ASPNETCORE_Kestrel__EndpointDefaults__Protocols=Http1AndHttp2
    depends_on:
      - xogamedb
    ports:
      - "8001:8080"

  authenticationservice:
    container_name: ludus-authenticationservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=Ludus;User Id=sa;Password=LudusBaza123!;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    ports:
      - "7000:8080"

  ludusgateways:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - Jwt__Key=fWZJY3tYTGdJWE1uZk1uTlRQd1dQemk0RXBnY0J3N1pmdG9VdkxORXRJWWVzTmxTYVJSQ0xYaz0=
      - Jwt__Issuer=http://authenticationservice:8080
      - Jwt__Audience=http://ludusgateways:8080
    depends_on:
      - xogamedb
      - xogameservice.api
    ports:
      - "8010:8080"

  matchmakingservice:
    container_name: matchmakingservice
    build:
      context: .
      dockerfile: Services/matchmaking/MatchmakingService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - RABBIT_HOST=rabbitmq
      - GAME_GRPC_ADDRESS=http://xogameservice.api:8080
    depends_on:
      - rabbitmq
      - xogameservice.api
    ports:
      - "5002:8080"
    
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"