version: "3.9"
services:
  matchmaking:
    build: ./services/matchmaking/MatchmakingService
    environment:
      - RABBIT_HOST=rabbitmq
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "5002:8080"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
